ALTER TABLE `wagons` ADD COLUMN IF NOT EXISTS (`water` INT(10) DEFAULT 0);
ALTER TABLE `farming` ADD COLUMN IF NOT EXISTS (`trimmed` VARCHAR(50) DEFAULT 0);
ALTER TABLE `farming` ADD COLUMN IF NOT EXISTS (`fertilized` VARCHAR(50) DEFAULT 0);
